title: SO17213
description: "Cybersecurity Consulting Portfolio – Segun O"
url: "https://so17213.github.io"
baseurl: ""
author: "Segun O"

theme: minima
plugins:
  - jekyll-feed
  - jekyll-seo-tag

# Define main navigation links
navbar-links:
  Home: "index"
  About Me: "about_me"
  Certifications: "certifications"
  Detection Engineering: "detection_engineering"
  Threat Hunting: "threat_hunting"
  Security Automation: "automation"
  Incident Response: "incident_response"
  Red Team: "red_team"
  Forensics: "forensics"
  Cloud Security: "cloud_security"
  SIEM Engineering: "SIEM_Engineering"
  Security Operations Center (SOC): "security_operation_center"
  Tools: "tools"

